### ISSUE TITLE
Updated Framework

### ISSUE THREAD

**Issue by Solilord** [TA2k/ioBroker.hoover#3]
Hey! 

<html><body>

hoover.0 | 2022-07-12 15:11:42.779 | error | "*/{\"event\":{\"descriptor\":\"markup://aura:clientOutOfSync\",\"eventDef\":{\"descriptor\":\"markup://aura:clientOutOfSync\",\"t\":\"APPLICATION\",\"xs\":\"I\"}},\"exceptionMessage\":\"Framework  has been updated. Expected: QPQi8lbYE8YujG6og6Dqgw Actual:  -SjNAdgW9yv96YgKI8MiFA\",\"exceptionEvent\":true}/*ERROR*/"
-- | -- | -- | --
hoover.0 | 2022-07-12 15:11:42.778 | error | Missing step1 url

</body>
</html>

Probably updated Framework by Hoover? ^^

**Comment by TA2k** [comment]
Please reinstall via github if this is fixed
