### ISSUE TITLE
Adapter bleibt Gelb

### ISSUE THREAD

**Issue by PalmManiac** [TA2k/ioBroker.hoover#7]
**Describe the bug**  
Obwohl der Adapter zu laufen scheint und das Gerät an ist, geht er nicht auf Grün. Es werden auch keine Fehler ins Log eingetragen, da steht als letzte Meldung nur "1 Gerät gefunden".

**Versions:**  
 - Adapter version: 0.0.6 (Latest)
 - JS-Controller version: 4.0.24
 - Node version: 18.7.0
 - Operating system: Ubuntu 22.10 LXC

**Comment by TA2k** [comment]
fixed in GitHub
